name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  frontend-tests:
    name: Frontend Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install dependencies
      run: |
        cd frontend
        npm ci
    
    - name: Run linting
      run: |
        cd frontend
        npm run lint
    
    - name: Build frontend
      run: |
        cd frontend
        npm run build

  backend-tests:
    name: Backend Tests  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        extensions: sqlite3, pdo_sqlite
    
    - name: Validate PHP syntax
      run: find . -name "*.php" -not -path "./vendor/*" -not -path "./frontend/node_modules/*" -exec php -l {} \;
    
    - name: Check code style (if php-cs-fixer is available)
      run: |
        if command -v php-cs-fixer &> /dev/null; then
          php-cs-fixer fix --dry-run --diff --config=.php-cs-fixer.php
        else
          echo "php-cs-fixer not available, skipping style check"
        fi

  docker-build:
    name: Docker Build Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Test development build
      run: |
        docker compose -f docker-compose.dev.yml build --no-cache
    
    - name: Test container startup
      run: |
        docker compose -f docker-compose.dev.yml up -d
        sleep 30
        docker compose -f docker-compose.dev.yml ps
        docker compose -f docker-compose.dev.yml down

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
    
    - name: Upload Trivy scan results
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'